[project]
name = "conversation-bot"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "gradio>=5.47.2",
    "langchain-openai>=0.3.33",
    "langgraph>=0.6.8",
    "openai>=1.109.1",
    "openai-agents>=0.3.2",
    "python-dotenv>=1.1.1",
]
